name: Go

on: [push, pull_request]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    
    - name: Install swig and gmp
      shell: bash
      run: sudo apt-get install -y swig libgmp-dev

    - name: Install mcl
      shell: bash
      run: |
        git clone --depth 1 https://github.com/herumi/mcl.git  && \
        cd mcl && \ 
        make install && \ 
        ldconfig

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      
    - uses: actions/checkout@v2
      
    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Run Unit tests.
      run: make test
      
