name: Go

on:
  push:
    branches:
      - master
      - release/*
      - collaborative-learning
  pull_request:
    branches:
      - master
      - release/*
      - collaborative-learning

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Install system dependencies
      shell: bash
      run: sudo apt-get install -y swig libboost-all-dev libgmp-dev git wget cmake

    - name: Install mcl
      run: |
        wget https://github.com/herumi/mcl/archive/v1.05.tar.gz &&\
        tar xvf v1.05.tar.gz && cd mcl-1.05 && \
        sudo make install

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Run end to end tests.
      run: |
        make build
        sudo cp ./build/tendermint /usr/local/bin
        sudo cp /usr/local/lib/libmcl.so /usr/lib/libmcl.so
        ./scripts/end_to_end_test.py

    - name: Run Unit tests.
      run: |
        export LD_RUN_PATH=/usr/local/lib
        make test

    - name: Run Native tests.
      run: |
        export LD_RUN_PATH=/usr/local/lib
        make test_native


